### ISSUE TITLE
Some SynGO evidence codes are no longer children of IDA

### ISSUE THREAD

**Issue by kltm** [geneontology/syngo2lego_data_conversion#5]
In the SynGO data, these evidence codes should be replaced so that they map up to IDA:

* ECO:0000164 electrophysiology assay evidence > should be changed to ECO:0006006 electrophysiology assay evidence used in manual assertion
* ECO:0001120 radioisotope assay evidence > should be changed to ECO:0001254 radioisotope assay evidence used in manual assertion
* ECO:0005593 immunodetection assay evidence > ECO:0007719 immunodetection assay evidence used in manual assertion
* ECO:0006065 in vitro cell based assay evidence used in manual assertion > obsolete, should be replaced by ECO:0007695
    name: cell-based assay evidence used in manual assertion

Tagging @pgaudet @dustine32

**Comment by pgaudet** [comment]
@ftwkoopmans Can you change the SynGO data as shown in the previous comment and generate a new json file? We could then reload the SynGO data and have everything consistent. 

Thanks, Pascale

**Comment by dustine32** [comment]
Noting that `ECO:0006065` is no longer present in the latest JSON file ([SynGO_export_2021-02-25.json](https://raw.githubusercontent.com/geneontology/syngo2lego_data_conversion/master/json/SynGO_export_2021-02-25.json)) so this term's usage appears to already be "fixed" in the upstream. The reason we are currently seeing `ECO:0006065` coming out of Noctua is because an older JSON file ([SynGO_export_2018-03-17.json](https://raw.githubusercontent.com/geneontology/syngo2lego_data_conversion/master/json/SynGO_export_2018-03-17.json)) is still loaded into Noctua production.

The other evidence terms `ECO:0000164`, `ECO:0001120`, `ECO:0005593` are still in the latest (2021-02-25) file and will need to be addressed.

**Comment by ftwkoopmans** [comment]
I've updated the JSON and uploaded it just now

**Comment by dustine32** [comment]
Thank you so much @ftwkoopmans!

**Comment by kltm** [comment]
@dustine32 Sorry to keep bugging you today, but I believe the next steps would be:

- [x] updating the models in `syngo-go-cam`
- [ ] coordinating an "overlay" event during one of the future outages (so we don't get too wonky with master being out of sync)

**Comment by kltm** [comment]
Pinging @vanaukenk to make sure that the second one there is on our radar.

**Comment by dustine32** [comment]
@kltm That's correct. I've been meaning to dust off [syngo2lego](https://github.com/geneontology/syngo2lego) for a long while.

**Comment by pgaudet** [comment]
- All obsolete evidence codes have been removed, see https://github.com/geneontology/syngo-go-cams/issues/3
- SynGO update planned for the 2022-07-14 Noctua outage, see https://github.com/geneontology/noctua/issues/782

Can this be closed @kltm ?

**Comment by kltm** [comment]
@pgaudet Techincally not fixed in production, so moved to clearing until finalized.

**Comment by kltm** [comment]
`release` is out.
